Repository SUSE/rmt, pull requests merged in 2024-11, with the labels that each got.

#1215 Use text instead of string as it can be limiting for paths length
  db/migrate/20240821114908_change_local_path_type.rb
  db/schema.rb
  package/obs/rmt-server.changes
Labels: 2.20

#1226 Fix SCC activations check when no product info is available
  engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
  engines/scc_proxy/lib/scc_proxy/engine.rb
Labels: Public Cloud

#1225 Check LTSS product to verify
  engines/zypper_auth/lib/zypper_auth/engine.rb
Labels: Public Cloud

#1241 Yabeda integration for prom metrics
  .env.example
  .github/workflows/lint-unit.yml
  .simplecov
  Gemfile
  Gemfile.lock
  config/initializers/yabeda.rb
  config/puma.rb
  config/puma/prometheus.rb
  config/rmt.yml
  config/routes.rb
  lib/rmt/config.rb
  package/obs/rmt.conf
Labels: enhancement
