Repository SUSE/rmt, pull requests merged in 2025-04, with the labels that each got.

#1306 Handle null client
  engines/registry/app/models/access_scope.rb
  engines/registry/app/models/registry/authenticated_client.rb
  engines/registry/app/services/registry_catalog_service.rb
  engines/registry/spec/app/models/access_scope_spec.rb
  engines/registry/spec/app/services/registry_catalog_service_spec.rb
Labels: 2.22

#1315 Background job dependencies
  DEVELOPMENT.md
  Gemfile
  Gemfile.lock
  package/obs/rmt-server.changes
  package/obs/rmt-server.spec
Labels: enhancement, dependencies, open for review, Public Cloud, 2.22

#1321 Update source code with proofread strings
  app/controllers/api/connect/v3/systems/products_controller.rb
  lib/rmt/cli/export.rb
  lib/rmt/cli/import.rb
  locale/rmt.pot
  spec/requests/api/connect/v3/systems/products_controller_spec.rb
  spec/support/shared_examples/product_checks.rb
Labels: open for review

#1323 Do not export BYOS systems to the Firehose bucket
  engines/data_export/lib/data_export/engine.rb
  engines/data_export/spec/requests/api/connect/v3/systems/systems_controller_spec.rb
Labels: Public Cloud, 2.22

#1319 Make SCC query and update cache
  engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
  engines/scc_proxy/lib/scc_proxy/engine.rb
Labels: Public Cloud, 2.22

#1317 Add upgrade cache check
  engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
Labels: enhancement, Public Cloud, 2.22

#1324 Error handling for hybrid system being announced to SCC
  engines/scc_proxy/lib/scc_proxy/engine.rb
  engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
Labels: Public Cloud

#1314 Update cache key
  engines/instance_verification/config/environments/development.rb
  engines/instance_verification/lib/instance_verification/engine.rb
  engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
  engines/registry/lib/registry/engine.rb
  engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
  engines/scc_proxy/lib/scc_proxy/engine.rb
  engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
  engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
  engines/strict_authentication/spec/requests/strict_authentication/authentication_controller_spec.rb
  engines/zypper_auth/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
  engines/zypper_auth/spec/requests/services_controller_spec.rb
  engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
Labels: Public Cloud, 2.22

#1318 Add subscription check cache
  engines/instance_verification/lib/instance_verification/engine.rb
  engines/instance_verification/spec/requests/api/connect/v3/systems/products_controller_spec.rb
  engines/registry/app/controllers/registry/registry_controller.rb
  engines/registry/app/models/access_scope.rb
  engines/registry/spec/app/models/access_scope_spec.rb
  engines/registry/spec/requests/api/connect/v3/systems/activations_controller_spec.rb
  engines/scc_proxy/lib/scc_proxy/engine.rb
  engines/scc_proxy/spec/requests/api/connect/v3/systems/products_controller_spec.rb
  engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb
  engines/zypper_auth/spec/requests/strict_authentication/authentication_controller_spec.rb
  spec/factories/systems.rb
Labels: Public Cloud, 2.22

#1322 Export data when system activates or upgrades a product
  engines/data_export/lib/data_export/engine.rb
  engines/data_export/spec/requests/api/connect/v3/systems/products_controller_spec.rb
  engines/data_export/spec/requests/api/connect/v3/systems/systems_controller_spec.rb
Labels: Public Cloud, 2.22

#1309 Option to not parse repodata file when it's unchanged
  MANUAL.md
  config/rmt.yml
  lib/rmt/config.rb
  lib/rmt/downloader.rb
  lib/rmt/mirror/base.rb
  lib/rmt/mirror/debian.rb
  lib/rmt/mirror/repomd.rb
  package/obs/rmt-server.changes
  package/obs/rmt.conf
  spec/lib/rmt/config_spec.rb
  spec/lib/rmt/mirror/debian_spec.rb
  spec/lib/rmt/mirror/repomd_spec.rb
Labels: 2.22
